CREATE TABLE IF NOT EXISTS `car`(
  `carid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '车辆ID',
  `carno` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '车牌号',
  `gpsid` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '车辆GPS编号',
  `userid` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'GPS所属用户ID',
  `driver` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '司机姓名',
  `mobile` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '司机手机号',
  `created` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '车辆添加时间',
  `lastid` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '车辆最后所在的GPS位置ID',
  `carstatus` TINYINT(3) NOT NULL DEFAULT '1' COMMENT '车辆状态',
  `driverstatus` TINYINT(3) NOT NULL DEFAULT '1' COMMENT '司机状态',
  `lockstatus` TINYINT(3) NOT NULL DEFAULT '1' COMMENT '电子锁状态',
  PRIMARY KEY (`carid`)
) ENGINE=Innodb DEFAULT CHARSET=utf8 COMMENT='车辆表' AUTO_INCREMENT=3;


CREATE TABLE IF NOT EXISTS `user`(
  `userid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `username` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户账号',
  `realname` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户姓名',
  `mobile` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '用户手机号',
  `email` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '邮箱地址',
  `password` CHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
  `group` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '用户分组',
  `created` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '注册时间',
  `status` TINYINT(3) NOT NULL DEFAULT '1' COMMENT '用户状态',
  PRIMARY KEY (`userid`)
) ENGINE=Innodb DEFAULT CHARSET=utf8 AUTO_INCREMENT=4;


CREATE TABLE IF NOT EXISTS `gps`(
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `gpsid` VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'GPSID',
  `longitude` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '经度',
  `latitude` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '纬度',
  `speed` DOUBLE(8,3) UNSIGNED NOT NULL DEFAULT '0.000' COMMENT '速度',
  `direction` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '方向',
  `location` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '位置名称',
  `extra` TEXT NOT NULL COMMENT '附加数据',
  `created` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '定位时间',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1' COMMENT '定位状态：1有效定位，0无效定位',
  PRIMARY KEY (`id`),
  KEY `carid` (`gpsid`)
) ENGINE=Innodb DEFAULT CHARSET=utf8 COMMENT='GPS坐标信息' AUTO_INCREMENT=79;
